<a href="https://colab.research.google.com/github/ufuomaibude/CUSTOMER-PROFILING-AND-CONVERSION-OPTIMIZATION-IN-FREIGHT-CRM-A-DATA-DRIVEN-ANALYSIS/blob/main/DataPreprocessing_Ufuoma.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

### import datasets

##Mount dataset on google drive: Quote details

In [ ]:
hubspot_data = pd.read_excel('/content/hubspot_dataoriginal.xlsx')
hubspot_data

,Record ID,Tudor Contact,Company Name,Export From,Import To,Transport Mode,Prospect Postcode,COST IN,QUOTE OUT,Last Communication Date,Given us a job?,Source,Regular Customer?,Quote Details,Lead Status,Last Activity Date,Create Date,Last Modified Date
0,57466897290,Adam Johnson,Clayworks Ltd,UK,Saudi Arabia,Air,TR12 7AZ,1250.0,1395.0,2024-09-27,NaN,Double Denim,NaN,"Collect from: TR12 7AZ, UK\nArrival at: Jeddah...",NaN,NaT,2024-09-12 15:40:00,2024-09-27 15:57:00
1,57419121966,Adam Johnson,Franco Finishes Ltd,United Arab Emirates,Qatar,Air,GARSTANG,2067.0,2310.0,2024-09-27,NaN,Double Denim,NaN,"Collect from: Garstang, UK\nArrival at: Doha A...",NaN,NaT,2024-09-12 12:15:00,2024-09-27 15:55:00
2,56611537189,Adam Johnson,Berry Global,UK,South Africa,Air,NN10 8RP,427.0,666.0,2024-09-27,NaN,Double Denim,NaN,"Collect from: NN10 8RP, UK\nArrival at: 2170, ...",NaN,NaT,2024-09-10 12:31:00,2024-09-27 15:53:00
3,56325263724,Adam Johnson,Dewi Lewis Publishing,UK,United States of America,Courier,SG13 7DT,940.0,1135.0,2024-09-27,NaN,Double Denim,NaN,"Collect from: SG13 7DT, UK\nArrival at: Freder...",NaN,NaT,2024-09-09 14:16:00,2024-09-27 15:52:00
4,55413343848,Adam Johnson,Bricky's Buddy Ltd,UK,Australia,Air,DL8 1XF,1116.0,1340.0,2024-09-27,NaN,Double Denim,NaN,"Collect from: DL8 1XF, UK\nDeliver to: 8-20 Br...",NaN,NaT,2024-09-06 10:14:00,2024-09-27 15:50:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3035,23695096734,Adam Johnson,NaN,UK,GHANA,Sea - LCL,Tudor,NaN,NaN,2024-05-22,NaN,NaN,NaN,"SEA FREIGHT QUOTATION\n\nLoad from: Tudor, UK\...",NaN,NaT,2024-05-23 12:44:00,2024-05-30 10:20:00
3036,23699011645,Adam Johnson,SPECIALIST LOGISTICS,NETHERLANDS,SUDAN,Sea - LCL,Rotterdam,NaN,NaN,2024-05-28,NaN,NaN,NaN,SEA FREIGHT QUOTATION\n\nCollect from: Lagaay ...,NaN,NaT,2024-05-23 12:55:00,2024-05-30 10:19:00
3037,23712767003,Adam Johnson,Texla DMCC,UK,DUBAi,Air,HU3 2DU,NaN,NaN,2024-05-03,NaN,NaN,NaN,AIR FREIGHT QUOTATION\n\nCollect from: HU3 2DU...,NaN,NaT,2024-05-23 13:57:00,2024-05-30 10:18:00
3038,23712771897,Stephen Sunderland,SPECIALIST LOGISTICS,NETHERLANDS,SUDAN,Air,Rotterdam,NaN,NaN,2024-05-21,NaN,NaN,NaN,AIR FREIGHT QUOTATION\n\nCollect from: Lagaay ...,NaN,NaT,2024-05-23 14:13:00,2024-05-30 10:17:00
3039,23712773782,Adam Johnson,SPECIALIST LOGISTICS,PORTUGAL,SUDAN,Air,Portugal,NaN,NaN,2024-05-02,NaN,NaN,NaN,AIR FREIGHT QUOTATION\n\nCollect from: Vipfarm...,NaN,NaT,2024-05-23 14:19:00,2024-05-30 10:17:00

In [ ]:
hubspot_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3040 entries, 0 to 3039
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Record ID                3040 non-null   int64
 1   Tudor Contact            3030 non-null   object
 2   Company Name             2802 non-null   object
 3   Export From              3009 non-null   object
 4   Import To                3036 non-null   object
 5   Transport Mode           3032 non-null   object
 6   Prospect Postcode        2980 non-null   object
 7   COST IN                  281 non-null    float64
 8   QUOTE OUT                303 non-null    float64
 9   Last Communication Date  3012 non-null   datetime64[ns]
 10  Given us a job?          305 non-null    object
 11  Source                   384 non-null    object
 12  Regular Customer?        302 non-null    object
 13  Quote Details            3040 non-null   object
 14  Lead Status              0 non-null      float64
 15  Last Activity Date       14 non-null     datetime64[ns]
 16  Create Date              3040 non-null   datetime64[ns]
 17  Last Modified Date       3040 non-null   datetime64[ns]
dtypes: datetime64[ns](4), float64(3), int64(1), object(10)
memory usage: 427.6+ KB

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

##Mount dataset on google drive: cost estimate

In [ ]:
sage_data = pd.read_excel('/content/sage_original data.xlsx')
sage_data

,Record ID,Tudor Contact,Company Name,Export From,Import To,Phone Number,Transport Mode,Prospect Postcode,COST IN,QUOTE OUT,...,Source,Regular Customer?,Quote Details,Lead Status,Last Activity Date,Create Date,Last Modified Date,Job Title,utm_source,utm_campaign
0,62398624126,Charlotte Firth,Novex,Spain,UK,4.401207e+12,Road,CO4 9QR,460.00,595.00,...,Phone call,NaN,2 PALLETS/ 497 KGS,NaN,NaN,2024-09-27 11:35:00,2024-09-27 11:36:00,NaN,NaN,NaN
1,62398623837,Charlotte Firth,Infinex,India,UK,4.475844e+11,Air,WD6 3AW,675.00,990.50,...,Phone call,NaN,11 CARTONS/ 100 KGS,NaN,NaN,2024-09-27 11:33:00,2024-09-27 11:34:00,NaN,NaN,NaN
2,62392132625,Charlotte Firth,mermaid leisure ltd,United States of America,UK,4.415808e+11,Sea - LCL,TN18 5LE,500.00,625.00,...,Double Denim,NaN,NaN,NaN,NaN,2024-09-27 10:41:00,2024-09-27 11:28:00,NaN,DD_google_ads_Q3_2024,international_pallet_shipping
3,62374704273,Charlotte Firth,Oddcolours Ltd,Italy,UK,4.417885e+11,Road,CV22 7LY,325.00,395.00,...,Double Denim,NaN,NaN,NaN,NaN,2024-09-27 10:31:00,2024-09-27 11:30:00,NaN,DD_google_ads_Q3_2024,international_pallet_shipping
4,57726862653,Adam Johnson,WSCCL,UK,USA,4.401133e+12,Courier,LS28 6QJ,379.00,479.00,...,Referral,NaN,"AIR\nCollect from: LS28 6QJ, UK\nArrival at: S...",NaN,NaN,2024-09-13 11:18:00,2024-09-23 19:45:00,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,2910,Luke McCrum,Yeoman Shield,UK,FINLAND,4.401133e+12,Air,Leeds,141.50,245.00,...,Referral,NaN,"DOOR TO DOOR QUOTATION\n\nCollect from: Leeds,...",NaN,NaN,2019-09-13 16:38:00,2024-07-24 11:08:00,Export Manager,NaN,NaN
321,6106,Adam Johnson,ENKAHNZ,UK,CANADA,4.401275e+12,Sea - LCL,Bradford,671.77,1095.00,...,Referral,Yes,SEA FREIGHT QUOTATION\n\nCollect from: Bradfor...,NaN,NaN,2019-09-13 16:38:00,2024-07-22 16:33:00,NaN,NaN,NaN
322,6058,Cat Badila,MARKETYZERS,UK,KUWAIT,9.655600e+10,Sea - FCL,TQ11 0LT,3821.00,4421.00,...,Referral,No,"CONTAINER QUOTATION\n\nCollect from: TQ11 0LT,...",NaN,NaN,2019-09-13 16:38:00,2024-07-26 13:12:00,NaN,NaN,NaN
323,5954,Cat Badila,VIAMASTER INTERNATIONAL LIMITED,UK,CHINA,4.411326e+11,Air,Leeds,657.22,957.22,...,Referral,Yes,"AIR FREIGHT QUOTATION\n\nCollect from: Spinks,...",NaN,NaN,2019-09-13 16:38:00,2024-07-26 16:16:00,NaN,NaN,NaN
324,5603,Luke McCrum,IMPS(UK)Ltd,UK,IRAN,4.401523e+12,Air,LN6 3LQ,240.00,350.00,...,Email - exports@,NaN,AIR FREIGHT QUOTATION\n\nCollect from: Lincoln...,NaN,NaN,2019-09-13 16:38:00,2024-07-24 11:54:00,NaN,NaN,NaN

In [ ]:
sage_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Record ID                325 non-null    int64
 1   Tudor Contact            321 non-null    object
 2   Company Name             275 non-null    object
 3   Export From              325 non-null    object
 4   Import To                325 non-null    object
 5   Phone Number             279 non-null    float64
 6   Transport Mode           323 non-null    object
 7   Prospect Postcode        301 non-null    object
 8   COST IN                  325 non-null    float64
 9   QUOTE OUT                325 non-null    float64
 10  Last Communication Date  318 non-null    datetime64[ns]
 11  Given us a job?          40 non-null     object
 12  Source                   320 non-null    object
 13  Regular Customer?        38 non-null     object
 14  Quote Details            281 non-null    object
 15  Lead Status              0 non-null      float64
 16  Last Activity Date       0 non-null      float64
 17  Create Date              325 non-null    datetime64[ns]
 18  Last Modified Date       325 non-null    datetime64[ns]
 19  Job Title                3 non-null      object
 20  utm_source               19 non-null     object
 21  utm_campaign             19 non-null     object
dtypes: datetime64[ns](3), float64(5), int64(1), object(13)
memory usage: 56.0+ KB

In [ ]:
hubspot_data = pd.read_excel('/content/hubspot_data.xlsx')

In [ ]:
hubspot_data2 = pd.read_excel('/content/new_hubspot&sage_aftermerge.xlsx')

In [ ]:
hubspot_data2

      Company Name(Hubspot)         Company Name
0                Clayworks                 Novex
1          Franco Finishes               Infinex
2              Berry Global  mermaid leisure ltd
3     Dewi Lewis Publishing          Oddcolours
4           Bricky's Buddy                 WSCCL
...                     ...                  ...
3035                    NaN                  NaN
3036   SPECIALIST LOGISTICS                  NaN
3037             Texla DMCC                  NaN
3038   SPECIALIST LOGISTICS                  NaN
3039   SPECIALIST LOGISTICS                  NaN

[3040 rows x 2 columns]

## Label company names found in Quote dataset

In [ ]:
company_names = set(hubspot_data['Company Name'].unique())

In [ ]:
hubspot_data['Converted']= hubspot_data['Company Name'].apply(lambda x: 1 if x in company_names else 0)

In [ ]:
hubspot_data

,Record ID,Tudor Contact,Company Name,Export From,Import To,Transport Mode,Prospect Postcode,COST IN,QUOTE OUT,Last Communication Date,Given us a job?,Source,Regular Customer?,Quote Details,Lead Status,Last Activity Date,Create Date,Last Modified Date,Converted
0,57466897290,Adam Johnson,Clayworks Ltd,UK,Saudi Arabia,Air,TR12 7AZ,1250.0,1395.0,2024-09-27,NaN,Double Denim,NaN,"Collect from: TR12 7AZ, UK\nArrival at: Jeddah...",NaN,NaT,2024-09-12 15:40:00,2024-09-27 15:57:00,1
1,57419121966,Adam Johnson,Franco Finishes Ltd,United Arab Emirates,Qatar,Air,GARSTANG,2067.0,2310.0,2024-09-27,NaN,Double Denim,NaN,"Collect from: Garstang, UK\nArrival at: Doha A...",NaN,NaT,2024-09-12 12:15:00,2024-09-27 15:55:00,1
2,56611537189,Adam Johnson,Berry Global,UK,South Africa,Air,NN10 8RP,427.0,666.0,2024-09-27,NaN,Double Denim,NaN,"Collect from: NN10 8RP, UK\nArrival at: 2170, ...",NaN,NaT,2024-09-10 12:31:00,2024-09-27 15:53:00,1
3,56325263724,Adam Johnson,Dewi Lewis Publishing,UK,United States of America,Courier,SG13 7DT,940.0,1135.0,2024-09-27,NaN,Double Denim,NaN,"Collect from: SG13 7DT, UK\nArrival at: Freder...",NaN,NaT,2024-09-09 14:16:00,2024-09-27 15:52:00,1
4,55413343848,Adam Johnson,Bricky's Buddy Ltd,UK,Australia,Air,DL8 1XF,1116.0,1340.0,2024-09-27,NaN,Double Denim,NaN,"Collect from: DL8 1XF, UK\nDeliver to: 8-20 Br...",NaN,NaT,2024-09-06 10:14:00,2024-09-27 15:50:00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3035,23695096734,Adam Johnson,NaN,UK,GHANA,Sea - LCL,Tudor,NaN,NaN,2024-05-22,NaN,NaN,NaN,"SEA FREIGHT QUOTATION\n\nLoad from: Tudor, UK\...",NaN,NaT,2024-05-23 12:44:00,2024-05-30 10:20:00,1
3036,23699011645,Adam Johnson,SPECIALIST LOGISTICS,NETHERLANDS,SUDAN,Sea - LCL,Rotterdam,NaN,NaN,2024-05-28,NaN,NaN,NaN,SEA FREIGHT QUOTATION\n\nCollect from: Lagaay ...,NaN,NaT,2024-05-23 12:55:00,2024-05-30 10:19:00,1
3037,23712767003,Adam Johnson,Texla DMCC,UK,DUBAi,Air,HU3 2DU,NaN,NaN,2024-05-03,NaN,NaN,NaN,AIR FREIGHT QUOTATION\n\nCollect from: HU3 2DU...,NaN,NaT,2024-05-23 13:57:00,2024-05-30 10:18:00,1
3038,23712771897,Stephen Sunderland,SPECIALIST LOGISTICS,NETHERLANDS,SUDAN,Air,Rotterdam,NaN,NaN,2024-05-21,NaN,NaN,NaN,AIR FREIGHT QUOTATION\n\nCollect from: Lagaay ...,NaN,NaT,2024-05-23 14:13:00,2024-05-30 10:17:00,1
3039,23712773782,Adam Johnson,SPECIALIST LOGISTICS,PORTUGAL,SUDAN,Air,Portugal,NaN,NaN,2024-05-02,NaN,NaN,NaN,AIR FREIGHT QUOTATION\n\nCollect from: Vipfarm...,NaN,NaT,2024-05-23 14:19:00,2024-05-30 10:17:00,1

## Compare both excel sheets 'hubspot_data' and 'sage_data'.

In [ ]:
import openpyxl

In [ ]:
from openpyxl.styles import PatternFill

Load both datasets using openpyxl

In [ ]:
hubspot_details = openpyxl.load_workbook('/content/hubspot_data.xlsx')
sage_details = openpyxl.load_workbook('/content/sage_data.xlsx')

print(sage_details)

<openpyxl.workbook.workbook.Workbook object at 0x7ba8f64b3a50>

In [ ]:
print(hubspot_details.sheetnames)

['main sheet']

In [ ]:
print(hubspot_details.sheetnames)
print(sage_details.sheetnames)

['main sheet']
['Unassigned contacts']

In [ ]:
data_sheet_hubspot = hubspot_details['main sheet']
data_sheet_sage = sage_details['Unassigned contacts']

In [ ]:
#check each cell in the sheet for values
data_sheet_hubspot['G3041'].value

'Air'

In [ ]:
fill_style = openpyxl.styles.PatternFill(start_color='FD0835', end_color='FF0835', fill_type='solid')

##Iterate over all cells to compare contents of both sheets, and print out CONTENTS in both sheets 'data_sheet_hubspot' and 'data_sheet_sage'

In [ ]:
for row in data_sheet_hubspot:
  for cell in row:
    current_cell_value = cell.value
    cell_location = cell.coordinate
    if current_cell_value != data_sheet_sage[cell_location].value:
      cell.fill = fill_style

    print(cell.value)

Streaming output truncated to the last 5000 lines.



This includes the provision of the batteries under UN2794. We have assumed the cargo is in gauge.


2024-03-01 13:16:00
2024-05-30 12:07:00
Project cargo coordinator


31557151
Luke McCrum
JAMM PRINT & PRODUCTION PTY LTD
UK
USA
 +4402083317200
Sea - LCL
SE18 5NS


2024-04-08 00:00:00



SEA FREIGHT QUOTATION



Collect from: SE18

Arrival at: 20678

Pieces: 3

Total Weight: 1700 kgs

Total Volume:  4.32 cbm

Dimensions: 120*100*120 cm each

Goods: General cargo, non-haz



FREIGHT & DESTINATION COSTS: £1154.00




2024-03-13 15:40:00
2024-05-30 12:05:00
Account Handler


31557201
Luke McCrum
LEPROSY MISSION INTERNATIONAL
UK
NIGERIA
 +442083266767
Air
TW7


2024-02-05 00:00:00



AIR FREIGHT QUOTATION

Collect from: Brentford, UK

Arrival at: Abuja airport only

Pieces: 21 Pieces (packed safely and securely for transit)

Total Weight: 195 kilos

Dimensions: 1 @ 56 x 72 x 90 cm

                      20 @ 88 x 65 x 35 cm (728 kilos chargeable)

Goods:  Non – Hazardous Cargo

FREIGHT COST: GBP 3145.00


2024-03-13 15:41:00
2024-05-30 12:03:00



31557351
Luke McCrum

UK
LIBYA

Sea - LCL
RM10


2024-03-08 00:00:00



SEA FREIGHT QUOTATION      Collect from: Rainham, UKArrival at: Tripoli port onlyPieces: 4 Pallets (packed safely and securely for transit)Total Weight: 839 kilosTotal Volume: 6.37 CBMDimensions: 1 @ 120 x 100 x 145 cm                            2 @ 120 x 100 x 150 cm                            1 @ 120 x 80 x 108 cmGoods: Non-Hazardous CargoFREIGHT COST: GBP 1075.00


2024-03-13 15:42:00
2024-05-30 12:02:00



31557401
Luke McCrum
ISOMI
UK
JAMAICA
 +441619039797
Air
WA7 1SY


2024-03-08 00:00:00



DOOR TO DOOR QUOTATION

Collect from: Halton, UK

Delivered to: Kingston city limits, Jamaica

Pieces: 6 Pallets (packed safely and securely for transit)

Total Weight: 1800 kilos

Dimensions: 6 @ 200 x 100 x 130 cm (2600 kilos chargeable)

Goods:  Non – Hazardous Cargo

FREIGHT COST: GBP 13,750.00


2024-03-13 15:43:00
2024-05-30 12:02:00
Contracts Manager


31558651
Luke McCrum
SEIGI NV
UK
CHINA
 +5978672223
Air
PR7 4HJ


2024-03-08 00:00:00



AIR FREIGHT QUOTATION

Collect from: Lancashire, UK

Arrival at: Bangkok airport only

Pieces: 1 Pallet (packed safely and securely for transit)

Total Weight: 121 kilos

Dimensions: 1 @ 160 x 80 x 38 cm

Goods:  Non – Hazardous Cargo

FREIGHT COST: GBP 475.00


2024-03-13 16:45:00
2024-05-30 12:02:00
CEO


31558751
Luke McCrum
GEORGE H KIME & CO
UK
FRANCE
 +441205870282
Road
NG32 3HL


2024-03-08 00:00:00



ROAD FREIGHT QUOTATION

Collect from: Grantham, UK

Delivered to: 35370 Chateau Des Tesnieres, France

Pieces: 2 pallets (packed safely and securely for transit)

Total Weight: 500 kilos

Dimensions: 2 @ 120 x 100 x 100 cm

Goods:  Non – Hazardous Cargo

FREIGHT COST: GBP 425.00


2024-03-13 16:49:00
2024-05-30 12:01:00
Boston Network Co-ordinator


31559101
Luke McCrum
BERRY GLOBAL
UK
JORDAN
 +441603894815
Sea - LCL
NR7 9AL


2024-02-07 00:00:00



SEA FREIGHT QUOTATION

Collect from: Norwich, UK

Arrival at: Aqaba port only, Jordan

Pieces: 2 Pallets (packed safely and securely for transit)

Total Weight: 840 kilos

Total Volume: 3.456 CBM

Dimensions: 2 @ 120 x 100 x 144 cm

Goods: Non-Hazardous Cargo

FREIGHT COST: GBP 540.00


2024-03-13 16:54:00
2024-05-30 12:01:00
Despatch Assistant


31559251
Luke McCrum
MONSIDE
UK
INDIA
 +447393671200
Air; Courier
CM22 6JX


2024-03-08 00:00:00



DOOR TO DOOR QUOTATION

Collect from: CM22, UK

Delivered to: 394305 Gujarat, India

Pieces: 2 Boxes (packed safely and securely for transit)

Total Weight: 62 kilos

Dimensions: 2 @ 40 x 30 x 20 cm

Goods:  Non – Hazardous Cargo

FREIGHT COST: GBP 295.00



Note this is based on our last-minute rates so will need to be confirmed at time of booking as they are subject to change at any time.




2024-03-13 16:56:00
2024-05-30 12:00:00
Managing Director


31559252
Luke McCrum
OMG MARKETING
BELGIUM
ITALY
 +442084506111
Road



2024-02-06 00:00:00



ROAD FREIGHT QUOTATION

Collect from: 1861 Meise, Belgium

Delivered to: 23873 Missaglia, Italy

Pieces: 1 pallet (packed safely and securely for transit)

Total Weight: 250 kilos

Dimensions: 1 @ 120 x 80 x 165 cm

Goods:  Non – Hazardous Cargo

FREIGHT COST: GBP 595.00


2024-03-13 16:57:00
2024-05-30 12:00:00



31559301
Luke McCrum
THINK AMBIENT LTD
UK
JAPAN
 +81335420191
Sea - LCL
HU5 4HF


2024-03-08 00:00:00



SEA FREIGHT QUOTATION

Collect from: Hull, UK

Arrival at: 135 0023 Tokyo, Japan

Pieces: 3 Pallets (packed safely and securely for transit)

Total Weight: 1280 kilos

Total Volume: 3.9 CBM

Dimensions: 3 @ 114 x 114 x 100 cm

Goods: Non-Hazardous Cargo

FREIGHT COST: GBP 1595.00


2024-03-13 16:58:00
2024-05-30 11:59:00



31559351
Luke McCrum
Ned Freight
UK
UZBEKISTAN
 +310857441450
Road
MK8 8DA


2024-02-08 00:00:00



ROAD FREIGHT QUOTATION

ROAD FREIGHT QUOTATION

Collect from: Milton Keynes, UK

Delivered to: Customs terminal Tashkent only

Pieces: 1 pallet (packed safely and securely for transit)

Total Weight: 390 kilos

Dimensions: 1 @ 120 x 80 x 165 cm

Goods:  Hazardous Cargo

FREIGHT COST: GBP 3250.00


2024-03-13 16:59:00
2024-05-30 11:59:00



31559451
Luke McCrum
Writemedia Solutions Limited
UK
GAMBIA
 +4407311361107
Air
SA72


2024-02-08 00:00:00



AIR FREIGHT QUOTATION

Collect from: SA72, UK

Arrival at: Banjul airport only

Pieces: 11 Boxes (packed safely and securely for transit)

Total Weight: 75 kilos

Dimensions: 4 @ 82 x 16 x 49 cm

                            4 @ 68 x 12 x 46 cm

                            1 @ 46 x 17 x 16 cm

                            1 @ 54 x 29 x 26 cm

                            1 @ 39 x 31 x 22 cm (81 kilos chargeable)

Goods:  Non – Hazardous Cargo

FREIGHT COST: GBP 695.00



This is based on our air freight service with a transit time of approximately 3 - 4 days (Subject to space and availability).


2024-03-13 17:00:00
2024-05-30 11:59:00



6345696390
Kieran Hawthorn-Peel
Anne-Lynn
UK
ZIMBABWE
 +27694526227
Air
GU14 6JD


2024-03-25 00:00:00



AIR FREIGHT QUOTATION

Collect from: GU14 6JD, UK

Delivered to: Harare, Zimbabwe

Total weight: 1.3 Kilos

Dimensions: 1 @ 32 x 23 x 18 cm



EXPRESS

FREIGHT COST: GBP 179.00



This courier service carries a transit time of approximately 5-6 days.



ECONOMY

FREIGHT COST: GBP 145.00


2024-03-25 12:54:00
2024-05-30 11:57:00
Managing Directo


6362267749
Kieran Hawthorn-Peel
AirBridge
UK
SOUTH KOREA
 +97694499916
Air
BT41 1QS


2024-04-04 00:00:00



AIR FREIGHT QUOTATION

Collect from: BT41 1QS

Arrival at: ICN airport

Pieces: 6 (packed safely and securely for transit)

Total Weight: 101 kilos (125 volumetric weight)

Dimensions:

2 @ 47 x 43 x 50cm

4 @ 66 x 46 x 45cm

Goods: Laboratory diagnostic agent - Temp Controlled rate +2 +8 - Non – Hazardous Cargo

AIR FREIGHT COST: GBP 599.58

Temp Controlled rate +2 +8 collection and delivery to our warehouse: GBP 1494.00



This is based on our air freight service with a transit time of approximately 3 - 4 days (Subject to space and availability).


2024-03-25 13:31:00
2024-05-30 11:56:00



10496768370
Kieran Hawthorn-Peel
Home Pizza Ovens Ltd
UK
DUBAI

Air
KT22 9BB


2024-04-04 00:00:00



AIR FREIGHT QUOTATION

Door to door

Collect from: KT22 9BB, UK

Delivered to: Meadows 1, Dubai, UAE

Total weight: 60 Kilos

Dimensions: 1 @ 120 x 70 x 70 cm

FREIGHT COST: GBP 885.66



This courier service carries a transit time of approximately 3-4 days.



The above costs exclude any duties, taxes or any custom formalities which may be applicable at the destination.



Alternatively, please find another option for this one.



AIR FREIGHT QUOTATION

Collect from: KT22 9BB, UK

Delivered to: Dubai airport only

Total weight: 60 Kilos

Dimensions: 1 @ 120 x 70 x 70 cm

Goods:  Non – Hazardous Cargo

FREIGHT COST: GBP 440.00


2024-04-08 15:58:00
2024-05-30 11:55:00



10496770471
Adam Johnson
Dormakaba
UK
UK

Road
SG4 0UD


2024-04-04 00:00:00



ROAD FREIGHT QUOTATION

Collect from: SG4, UK
Arrival at: 31-33 Hillsborough Road, LISBURN, BT28 1JL

Pieces: 1 @ 210 x 120 x 40 cm / 100 kilos

Cost: £395.00


2024-04-08 16:02:00
2024-05-30 11:54:00



10497195361
Adam Johnson
Renouest distribution
ITALY
FRANCE
 +33780965072
Road



2024-04-05 00:00:00



ROAD FREIGHT QUOTATION

Collect from: 10050 Chiusa San Michele (TO)
Deliver to: 4 AVENUE PIERRE SALVI, 95500 GONESSE, FRANCE

Pieces: 31 @ 120 x 80 x 190 cm
Total Weight: 23780 kilos
Cost: £2,390.00


2024-04-08 16:04:00
2024-05-30 11:53:00
Purchases and Trade Department


10496771645
Adam Johnson
Beeveejay Limited
UK
CAMEROON
 +447876257114
Air
WD24 7QJ


2024-04-04 00:00:00



AIR FREIGHT QUOTATION

Collect from: Any UK address
Arrival at: Hospital Central Yaounde, Yaounde, Cameroon
Pieces: 1 @ 32 x 27 x 42 cm / 3 kilos
Cost: £195.00


2024-04-08 16:05:00
2024-05-30 11:53:00
Operations Manager


10496772018
Adam Johnson
King's Haulage
UK
ICELAND
 +4407887652351
Sea - LCL
TS6 6UD


2024-04-05 00:00:00



SEA FREIGHT QUOTATION

Collect from: You deliver to Teesport
Arrival at: 260 Reykjanesbaer, Iceland
Pieces: 10 @ 700 x 330 x 300 cm / 10,000 kilos each
Cost: £45,855.00


2024-04-08 16:06:00
2024-05-30 11:52:00
Managing Director


10501371971
Adam Johnson
Classic Performance Ltd
UK
AUSTRALIA
 +441908372316
Air
MK1


2024-04-04 00:00:00



AIR FREIGHT QUOTATION



Collect from: MK1

Arrival at: 6107, Australia

Pieces: 1

Total Weight: 180 kgs

Dimensions: 80*70*100 cm

Goods: General cargo, non-haz



FREIGHT COST: £1348.00

DESTINATION CHARGES: £345.00



TOTAL COST: £1693.00


2024-04-08 16:12:00
2024-05-30 11:52:00



10501372990
Jamie Halliday
Ewals Cargo Care Ltd
UK
AUSTRALIA
 +441206753323
Sea - LCL
ST3 5BW


2024-04-04 00:00:00



SEA FREIGHT QUOTATION



Collect from: ST3

Arrival at: Melbourne Port

Pieces: 1

Total Weight: 580 kgs

Total Volume:  6.86 cbm

Dimensions: 277*130*190 cm

Goods: General cargo, non-haz



FREIGHT COST: £595.00


2024-04-08 16:15:00
2024-05-30 11:45:00
Freight Management Supervisor


10501373767
Jamie Halliday
Floor store
UK
FRANCE
 +447572730343
Road
RG30 1EA


2024-02-13 00:00:00



ROAD FREIGHT QUOTATION

Collect: London



Deliver: Chambery, France



2 @ 120*100*100 cm / 100 kgs each



Total Cost: £365.00 DAP uncleared


2024-04-08 16:17:00
2024-05-30 11:45:00
Managing Director


10503458414
Jamie Halliday
Marinair
UK
MALAYSIA
 +31208083621
Air
BR5 3RE


2024-04-04 00:00:00



AIR FREIGHT QUOTATION



Collect from: BR5

Arrival at: KUL Airport Only

Pieces: 3

Total Weight: 176 kgs / 316 kgs chargeable weight

Dimensions: As per your email

Goods: General Cargo, non-haz



FREIGHT COST: £945.00


2024-04-08 16:35:00
2024-05-30 11:43:00



10503458878
Jamie Halliday
Zeco Ltd
UK
CYPRUS
 +4401708739390
Air
RM3 8SU


2024-05-21 00:00:00



DOOR TO DOOR QUOTATION

Collect from: RM3 8SU, UK

Delivered to: 2235 Latsia, 1584 Nicosia, Cyprus

Pieces: 5 boxes (packed safely and securely for transit)

Total Weight: 150 kilos

Dimensions: 5 @ 48 x 48 x 48 cm

Goods:  Non – Hazardous Cargo

FREIGHT COST: GBP 716.35 + VAT


2024-04-08 16:36:00
2024-05-30 11:43:00



10505631815
Jamie Halliday
Anodes Direct
UK
HONG KONG
 +4401621743540
Air; Sea - LCL
ME13


2024-04-04 00:00:00



AIR FREIGHT QUOTATION



Collect from: ME13

Arrival at: HKG Airport Only

Pieces: 1

Total Weight: 780 kgs

Dimensions: 120*80*35 cm

Goods: General Cargo, non-haz



FREIGHT COST: £1245.00

SEA FREIGHT QUOTATION



Collect from: ME13

Arrival at: HKG Port Only

Pieces: 1

Total Weight: 780 kgs

Total Volume:  0.33 cbm

Dimensions: 120*80*35 cm

Goods: General Cargo, non-haz



FREIGHT COST: £190.00


2024-04-08 16:51:00
2024-05-30 11:42:00



10503465992
Jamie Halliday
Havel worldwide shipping
UK
DUBAI
 +97167455635
Air
ML4 3NJ


2024-05-30 00:00:00



AIR FREIGHT QUOTATION



Collect from: ML4

Arrival at: DXB

Pieces: 4

Total Weight: 840 kgs

Dimensions: 120*80*173 cm each

Goods: General cargo, non-haz



FREIGHT COST: £2375.00


2024-04-08 16:52:00
2024-05-30 11:42:00



12514330511
Adam Johnson
Express Arabia
UK
SAUDI ARABIA
 +966545326111
Sea - FCL
NR34 7TB


2024-04-12 00:00:00



SEA FREIGHT QUOTATION

Please se our costs for your shipment to Saudi below:

Collect from: NR34 7TB, UK
Arrival at: Jeddah Port, Saudi Arabia
Equipment: 1 x 40HC
Cost: £3,326.00


2024-04-15 13:12:00
2024-05-30 11:41:00



12516220436
Adam Johnson
GKO Logistics services
UK
AZERBAIJAN
 +994105213454
Air
BD4 6NA


2024-04-04 00:00:00



Collect from: BD4 6NA, UK

Arrival at: GYD Airport, Azerbaijan
Pieces: 2 x pallets
1 @ 120 x 100 x 90 cm / 60 kilos
1 @ 120 x 100 x 91 cm / 60 kilos
Total Weight: 120 kilos
Chargeable Weight: 364 kilos (based on the size and shape of the shipment)
Cost: £1,290.00




2024-04-15 13:15:00
2024-05-30 11:41:00
Operations Manager


12516224013
Adam Johnson

UK
ARMENIA

Road
SO50


2024-04-12 00:00:00



ROAD FREIGHT QUOTATION

Collect from: SO50, UK

Arrival at: Yerevan city, Armenia
Pieces: 8 x pallets
4 @ 120 x 80 x 116 cm
2 @ 120 x 80 x 141 cm
1 @ 120 x 80 x 100 cm
1 @ 120 x 80 x 88 cm

Total Weight: 1014 kilos

Cost: £2,590.00


2024-04-15 13:30:00
2024-05-30 11:40:00



12531962517
Adam Johnson
ATLS
UK
TUNISIA
 +21629565623
Air
S80 2RS


2024-04-12 00:00:00



AIR FREIGHT QUOTATION

Collect from: S80 2RS, UK
Arrival at: Tunis Airport, Tunisia

Pieces: 9 @ 73 x 39 x 51 cm / 5 kilos each
Total Weight: 45 kilos
Chargeable Weight: 218 kilos
Cost: £725.00


2024-04-15 14:00:00
2024-05-30 11:39:00



12535810090
Jamie Halliday
SLRS SUPPLIES
UK
DUBAI

Air; Sea - LCL
IG8 8HH


2024-04-09 00:00:00



AIR FREIGHT QUOTATION



Collect from: IG8 8HH

Arrival at: Dubai Airport

Pieces: 3

Total Weight: 2500 kgs

Dimensions: 120*80*150 cm each

Goods: General Cargo, non-haz



FREIGHT COST: £3730.00

SEA FREIGHT QUOTATION



Collect from: IG8 8HH

Arrival at: Dubai Port

Pieces: 3

Total Weight: 2500 kgs

Total Volume:  4.32 cbm

Dimensions: 120*80*150 cm

Goods: General cargo, non-haz



FREIGHT COST: £356.00


2024-04-15 14:04:00
2024-05-30 11:38:00



12537078180
Jamie Halliday

UK
SAUDI ARABIA

Sea - LCL



2024-03-18 00:00:00



SEA FREIGHT QUOTATION

As discussed, please see our costs for shipping goods to Jeddah ex Wigan via LCL.



1 CBM: £236.00



3 CBM: £438.00



5 CBM: £632.00



10 CBM: £1175.00


2024-04-15 14:06:00
2024-05-30 11:37:00



12588447154
Jamie Halliday
ONE TIME CRITICAL TRANSPORT
GERMANY
SPAIN
 +441753682426
Road
46446


2024-04-09 00:00:00



ROAD FREIGHT QUOTATION

As discussed, please see below our costs to deliver the goods to Ibiza port only.



Freight Costs: £4695.00


2024-04-15 15:59:00
2024-05-30 11:34:00



12588810923
Jamie Halliday

UK
DENMARK

Road
EC1R 0AB


2024-04-09 00:00:00



ROAD FREIGHT QUOTATION

We can cover this shipment for £490.00 on a door-to-door basis.



We can insure the goods for £120.00.


2024-04-15 16:01:00
2024-05-30 11:34:00



12593228610
Jamie Halliday
Arvi international Shipping
UK
DUBAI
 +97143864592
Air
CO6 1TL


2024-04-09 00:00:00



AIR FREIGHT QUOTATION



Collect from: CO6

Arrival at: Dubai Amazon fulfilment centre, 999041, DXB2

Pieces: 5

Total Weight: 496 kgs / 554 kgs chargeable weight

Dimensions: As per your email

Goods: General cargo, non-haz



FREIGHT COST: £1275.00

DESTINATION COSTS: £437.00



TOTAL COST: £1712.00



2024-04-15 16:04:00
2024-05-30 11:32:00
Supply Chain and Operations Manager


12596505856
Jamie Halliday
Gazelle express services
UK
LIBYA
 +218912188552
Air



2024-03-25 00:00:00



AIR FREIGHT QUOTATION



Collect from: Birmingham

Arrival at: MJI Airport Only

Pieces: 2

Total Weight: 1000 kgs

Dimensions: 120*90*90 cm

Goods: General cargo, non-haz



FREIGHT COST: £8390.00


2024-04-15 16:30:00
2024-05-30 11:31:00



13310024473
Jamie Halliday
W4CO LTD
UK
GREECE
 +447831503475
Road
BS20 0DH


2024-04-09 00:00:00



ROAD FREIGHT QUOTATION

Please see below our costs for this shipment via road freight.



Total Cost: £1975.00 DAP uncleared.


2024-04-17 16:07:00
2024-05-30 11:31:00



12605243451
Jamie Halliday

UK
NEW YORK
 +447929257039
Sea - LCL



2024-04-09 00:00:00



SEA FREIGHT QUOTATION

Dubai to New York based on 1200 kgs / 0.48 cbm:



Total Cost: £295.00 (This is a port-to-port cost only and excludes any local or destination charges)



Transit time approx. 40 days.



Birmingham to New York based on 1200 kgs / 0.48 cbmL



Total Cost: £225.00 (This is a door-to-port cost only and excludes any destination charges)



Approx transit time 11 days.


2024-04-15 16:36:00
2024-05-30 11:31:00



13294473028
Jamie Halliday
Ennismore
UK
SPAIN

Courier; Road
SE1 8DP


2024-03-21 00:00:00



ROAD FREIGHT QUOTATION

Road Freight: £370.00 DAP uncleared



Approx transit time 7 – 10 days.



Courier: £345.00 DAP uncleared



Approx transit time 12 days.


2024-04-17 16:13:00
2024-05-30 11:29:00
Head of Graphic Design Services


13335342731
Jamie Halliday
Achieving for children
UK
ZIMBABWE
 +447598404052
Sea - LCL
KT3


2024-04-09 00:00:00



SEA FREIGHT QUOTATION



Collect from: KT3

Arrival at: Bluawayo Port Only

Pieces: 1

Total Weight: 100 kgs

Total Volume:  0.33 cbm

Dimensions: 59*59*96 cm

Goods: General cargo, non-haz



FREIGHT COST: £315.00


2024-04-17 16:49:00
2024-05-30 11:29:00
Targeted support worker


13318020485
Jamie Halliday
Advanced graphics
UK
AUSTRALIA
 +4402074072055
Sea - LCL
SE11 6SF


2024-04-08 00:00:00



SEA FREIGHT QUOTATION

Collect from: SE11
Arrival at: Melbourne Port Only
Pieces: 2
Total Weight: 110 kgs
Total Volume: 1 cbm
Dimensions: 116*86*46 cm / 166*134*25 cm
Goods: General cargo, non-haz

FREIGHT COST: £208.00

Approx transit time 45 - 50 days port to port.


2024-04-17 16:54:00
2024-05-30 11:28:00



13318022058
Jamie Halliday
Willem coffee
UK
EGYPT
 +4407449696820
Air
MK15


2024-04-08 00:00:00



AIR FREIGHT QUOTATION



Collect from: MK15

Arrival at: Cairo Airport Only

Pieces: 1

Total Weight: 70 kgs

Dimensions: 60*60*80 cm

Goods: General Crago, non-haz



FREIGHT COST: £385.00


2024-04-17 16:57:00
2024-05-30 11:27:00



13573614963
Jamie Halliday
Qanot Sharq LLC
UK
UZBEKISTAN
 +998909165057
Air
RH13 0AS


2024-04-08 00:00:00



AIR FREIGHT QUOTATION

1)PICK UP LOCATION:

AJW

A J Walter Aviation The Headquarters

Maydwell Avenue Slinfold West Sussex    RH13 0AS



Weight and Dims: BOX #1 - D: 66 x 66 x 66 сm/ W: 87 kg



Air Freight: £488.40 based on TK



2)

Rotable Repairs Limited

20 Progress Road,

Leigh On Sea,

Essex, SS9 5PR.

United Kingdom



Weight and Dims: BOX #1 - D: 120 x 118 x 60 cm / W: 200 kg



Air Freight: £875.00 based on TK



3)

PDQ Airspares Ltd

The Warehouse

Fairgate Centre,

Burgate, Fordingbridge

Hampshire

SP6 1LX



Weight and Dims:

BOX #1 - D: 62 x 46 x 48 cm / W: 11 kg

BOX #1 - D: 24 x 24 x 24 cm / W: 3 kg

BOX #1 - D: 24 x 24 x 24 cm / W: 0.5 kg



Air Freight: £285.00 based on TK (Chargeable weight 29 kgs)



4)

Watts Aviation Services Limited

Mead Lane, Lydney,

Gloucestershire, GL15 5EL, UK



Weight and Dims:

PALLET #1 - D: 130 x 115 x 148 cm / W: 334 kg

PALLET #2 - D: 130 x 115 x 155 cm / W: 379 kg



Air Freight: £2395.00 based on LH (Chargeable weight 755 kgs)




2024-04-18 11:41:00
2024-05-30 11:27:00
Procurement Specialist


13573821533
Jamie Halliday
Flyship logistics
UK
NETHERLANDS
 +442081444381
Road
IG11 0TJ


2024-05-23 00:00:00



ROAD FREIGHT QUOTATION

Total Cost: £290.00 DAP uncleared


2024-04-18 11:45:00
2024-05-30 11:27:00
Business Development Manager


13573821803
Jamie Halliday
Nature metrics
UK
MYANMAR
 +447827742723
Courier



2024-04-08 00:00:00



COURIER QUOTATION DETAILS

We can arrange this for £250.00


2024-04-18 11:46:00
2024-05-30 11:26:00
Logistics Manager


13577289047
Jamie Halliday
uk wallpaper
UK
ISRAEL
 +442392215830
Air
PO6 3BZ


2024-04-08 00:00:00



AIR FREIGHT QUOTATION



Collect from: PO6

Arrival at: Tel Aviv Airport Only

Pieces: 1 pallet

Total Weight: 450 kgs

Dimensions: tbc

Goods: General cargo, non-haz



FREIGHT COST: £1135.00


In [ ]:
hubspot_details.save('compareds_file.xlsx')

In [ ]:
compareds_file = pd.read_excel('/content/compareds_file.xlsx')

In [ ]:
compareds_file

,Record ID,Tudor Contact,Company Name,Export From,Import To,Phone Number,Transport Mode,Prospect Postcode,COST IN,QUOTE OUT,...,Source,Regular Customer?,Quote Details,Lead Status,Last Activity Date,Create Date,Last Modified Date,Job Title,utm_source,utm_campaign
0,57466897290,Adam Johnson,Clayworks Ltd,UK,Saudi Arabia,4.413263e+11,Air,TR12 7AZ,1250.0,1395.0,...,Double Denim,NaN,"Collect from: TR12 7AZ, UK\nArrival at: Jeddah...",NaN,NaT,2024-09-12 15:40:00,2024-09-27 15:57:00,NaN,DD_google_ads_Q3_2024,international_pallet_shipping
1,57419121966,Adam Johnson,Franco Finishes Ltd,United Arab Emirates,Qatar,4.477112e+11,Air,GARSTANG,2067.0,2310.0,...,Double Denim,NaN,"Collect from: Garstang, UK\nArrival at: Doha A...",NaN,NaT,2024-09-12 12:15:00,2024-09-27 15:55:00,NaN,DD_google_ads_Q3_2024,international_pallet_shipping
2,56611537189,Adam Johnson,Berry Global,UK,South Africa,4.477716e+11,Air,NN10 8RP,427.0,666.0,...,Double Denim,NaN,"Collect from: NN10 8RP, UK\nArrival at: 2170, ...",NaN,NaT,2024-09-10 12:31:00,2024-09-27 15:53:00,NaN,DD_google_ads_Q3_2024,international_pallet_shipping
3,56325263724,Adam Johnson,Dewi Lewis Publishing,UK,United States of America,4.478907e+11,Courier,SG13 7DT,940.0,1135.0,...,Double Denim,NaN,"Collect from: SG13 7DT, UK\nArrival at: Freder...",NaN,NaT,2024-09-09 14:16:00,2024-09-27 15:52:00,NaN,DD_google_ads_Q3_2024,international_pallet_shipping
4,55413343848,Adam Johnson,Bricky's Buddy Ltd,UK,Australia,4.475405e+11,Air,DL8 1XF,1116.0,1340.0,...,Double Denim,NaN,"Collect from: DL8 1XF, UK\nDeliver to: 8-20 Br...",NaN,NaT,2024-09-06 10:14:00,2024-09-27 15:50:00,NaN,DD_google_ads_Q3_2024,international_pallet_shipping
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3035,23695096734,Adam Johnson,NaN,UK,GHANA,NaN,Sea - LCL,Tudor,NaN,NaN,...,NaN,NaN,"SEA FREIGHT QUOTATION\n\nLoad from: Tudor, UK\...",NaN,NaT,2024-05-23 12:44:00,2024-05-30 10:20:00,NaN,NaN,NaN
3036,23699011645,Adam Johnson,SPECIALIST LOGISTICS,NETHERLANDS,SUDAN,9.715852e+11,Sea - LCL,Rotterdam,NaN,NaN,...,NaN,NaN,SEA FREIGHT QUOTATION\n\nCollect from: Lagaay ...,NaN,NaT,2024-05-23 12:55:00,2024-05-30 10:19:00,NaN,NaN,NaN
3037,23712767003,Adam Johnson,Texla DMCC,UK,DUBAi,9.715267e+11,Air,HU3 2DU,NaN,NaN,...,NaN,NaN,AIR FREIGHT QUOTATION\n\nCollect from: HU3 2DU...,NaN,NaT,2024-05-23 13:57:00,2024-05-30 10:18:00,General manager,NaN,NaN
3038,23712771897,Stephen Sunderland,SPECIALIST LOGISTICS,NETHERLANDS,SUDAN,9.714586e+10,Air,Rotterdam,NaN,NaN,...,NaN,NaN,AIR FREIGHT QUOTATION\n\nCollect from: Lagaay ...,NaN,NaT,2024-05-23 14:13:00,2024-05-30 10:17:00,NaN,NaN,NaN
3039,23712773782,Adam Johnson,SPECIALIST LOGISTICS,PORTUGAL,SUDAN,9.714586e+10,Air,Portugal,NaN,NaN,...,NaN,NaN,AIR FREIGHT QUOTATION\n\nCollect from: Vipfarm...,NaN,NaT,2024-05-23 14:19:00,2024-05-30 10:17:00,NaN,NaN,NaN

## OPEN EXCEL FILE AND SEE THE DIFFERENCES HIGHLIGHTED ON A SHEET TITLED 'new_sheet_quote'

## Remove all special characters in the hubspot_data including, brackets, 'ltd' and replace with a space.

In [ ]:
import re

In [ ]:
df = pd.read_excel("/content/hubspot_data.xlsx", sheet_name='main sheet')
df['Company Name'] = df['Company Name'].replace(r'\W'," ")
df['Company Name'] = df['Company Name'].str.replace(r'\b(Ltd|LTD|Limited|()|LIMITED|(UK))\b', '', regex=True)

print(df['Company Name'])

hubs_column = df['Company Name']
hubs_column.to_excel('hubs_column.xlsx')

0                  Clayworks
1            Franco Finishes
2                Berry Global
3       Dewi Lewis Publishing
4             Bricky's Buddy
                ...
3035                      NaN
3036     SPECIALIST LOGISTICS
3037               Texla DMCC
3038     SPECIALIST LOGISTICS
3039     SPECIALIST LOGISTICS
Name: Company Name, Length: 3040, dtype: object

In [ ]:
df.to_excel('/content/removed_characters.xlsx')

In [ ]:
print(df['Company Name'])

0                  Clayworks
1            Franco Finishes
2                Berry Global
3       Dewi Lewis Publishing
4             Bricky's Buddy
                ...
3035                      NaN
3036     SPECIALIST LOGISTICS
3037               Texla DMCC
3038     SPECIALIST LOGISTICS
3039     SPECIALIST LOGISTICS
Name: Company Name, Length: 3040, dtype: object

In [ ]:
df['Company Name'].to_excel('hubspotcolumn.xlsx')

In [ ]:
#Load the sage sheet and extract the 'Company Name' Column

##Remove all special characters and 'Ltd' from the 'sage data' and brackets and replace with an empty string ' '

In [ ]:
df2 = pd.read_excel('/content/sage_data.xlsx')
df2['Company Name'] = df2['Company Name'].replace(r'\W'," ")
df2['Company Name'] = df2['Company Name'].str.replace(r'\b(Ltd|LTD|ltd|Limited|LIMITED|(UK))\b', '', regex=True)

In [ ]:
df2['Company Name']

0                         Novex
1                       Infinex
2              mermaid leisure
3                   Oddcolours
4                         WSCCL
                 ...
320               Yeoman Shield
321                     ENKAHNZ
322                 MARKETYZERS
323    VIAMASTER INTERNATIONAL
324                      IMPS()
Name: Company Name, Length: 325, dtype: object

In [ ]:
df2['Company Name'].to_excel('sagecolumn.xlsx')

In [ ]:
from openpyxl import workbook
from openpyxl.styles import PatternFill
from openpyxl.utils.dataframe import dataframe_to_rows
import difflib

In [ ]:
df3 = pd.read_excel('/content/hubspot_data.xlsx')
df3

,Record ID,Tudor Contact,Company Name,Export From,Import To,Phone Number,Transport Mode,Prospect Postcode,COST IN,QUOTE OUT,...,Source,Regular Customer?,Quote Details,Lead Status,Last Activity Date,Create Date,Last Modified Date,Job Title,utm_source,utm_campaign
0,57466897290,Adam Johnson,Clayworks Ltd,UK,Saudi Arabia,4.413263e+11,Air,TR12 7AZ,1250.0,1395.0,...,Double Denim,NaN,"Collect from: TR12 7AZ, UK\nArrival at: Jeddah...",NaN,NaT,2024-09-12 15:40:00,2024-09-27 15:57:00,NaN,DD_google_ads_Q3_2024,international_pallet_shipping
1,57419121966,Adam Johnson,Franco Finishes Ltd,United Arab Emirates,Qatar,4.477112e+11,Air,GARSTANG,2067.0,2310.0,...,Double Denim,NaN,"Collect from: Garstang, UK\nArrival at: Doha A...",NaN,NaT,2024-09-12 12:15:00,2024-09-27 15:55:00,NaN,DD_google_ads_Q3_2024,international_pallet_shipping
2,56611537189,Adam Johnson,Berry Global,UK,South Africa,4.477716e+11,Air,NN10 8RP,427.0,666.0,...,Double Denim,NaN,"Collect from: NN10 8RP, UK\nArrival at: 2170, ...",NaN,NaT,2024-09-10 12:31:00,2024-09-27 15:53:00,NaN,DD_google_ads_Q3_2024,international_pallet_shipping
3,56325263724,Adam Johnson,Dewi Lewis Publishing,UK,United States of America,4.478907e+11,Courier,SG13 7DT,940.0,1135.0,...,Double Denim,NaN,"Collect from: SG13 7DT, UK\nArrival at: Freder...",NaN,NaT,2024-09-09 14:16:00,2024-09-27 15:52:00,NaN,DD_google_ads_Q3_2024,international_pallet_shipping
4,55413343848,Adam Johnson,Bricky's Buddy Ltd,UK,Australia,4.475405e+11,Air,DL8 1XF,1116.0,1340.0,...,Double Denim,NaN,"Collect from: DL8 1XF, UK\nDeliver to: 8-20 Br...",NaN,NaT,2024-09-06 10:14:00,2024-09-27 15:50:00,NaN,DD_google_ads_Q3_2024,international_pallet_shipping
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3035,23695096734,Adam Johnson,NaN,UK,GHANA,NaN,Sea - LCL,Tudor,NaN,NaN,...,NaN,NaN,"SEA FREIGHT QUOTATION\n\nLoad from: Tudor, UK\...",NaN,NaT,2024-05-23 12:44:00,2024-05-30 10:20:00,NaN,NaN,NaN
3036,23699011645,Adam Johnson,SPECIALIST LOGISTICS,NETHERLANDS,SUDAN,9.715852e+11,Sea - LCL,Rotterdam,NaN,NaN,...,NaN,NaN,SEA FREIGHT QUOTATION\n\nCollect from: Lagaay ...,NaN,NaT,2024-05-23 12:55:00,2024-05-30 10:19:00,NaN,NaN,NaN
3037,23712767003,Adam Johnson,Texla DMCC,UK,DUBAi,9.715267e+11,Air,HU3 2DU,NaN,NaN,...,NaN,NaN,AIR FREIGHT QUOTATION\n\nCollect from: HU3 2DU...,NaN,NaT,2024-05-23 13:57:00,2024-05-30 10:18:00,General manager,NaN,NaN
3038,23712771897,Stephen Sunderland,SPECIALIST LOGISTICS,NETHERLANDS,SUDAN,9.714586e+10,Air,Rotterdam,NaN,NaN,...,NaN,NaN,AIR FREIGHT QUOTATION\n\nCollect from: Lagaay ...,NaN,NaT,2024-05-23 14:13:00,2024-05-30 10:17:00,NaN,NaN,NaN
3039,23712773782,Adam Johnson,SPECIALIST LOGISTICS,PORTUGAL,SUDAN,9.714586e+10,Air,Portugal,NaN,NaN,...,NaN,NaN,AIR FREIGHT QUOTATION\n\nCollect from: Vipfarm...,NaN,NaT,2024-05-23 14:19:00,2024-05-30 10:17:00,NaN,NaN,NaN

## Calculate the percentage similarity between hubspot data and sage data

In [ ]:
import difflib


def similarity_percentage(str1, str2):
    # Get the similarity ratio
    ratio = difflib.SequenceMatcher(None, str1, str2).ratio()
    # Convert to percentage
    return ratio * 100

string1 = "df['Company Name]"
string2 = "df2['Company Name]"
similarity = similarity_percentage(string1, string2)
print(f"Similarity: {similarity:.2f}%")

Similarity: 97.14%

In [ ]:

!pip install fuzzywuzzy python-Levenshtein

Collecting fuzzywuzzy
  Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl.metadata (4.9 kB)
Collecting python-Levenshtein
  Downloading python_Levenshtein-0.26.1-py3-none-any.whl.metadata (3.7 kB)
Collecting Levenshtein==0.26.1 (from python-Levenshtein)
  Downloading levenshtein-0.26.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
Collecting rapidfuzz<4.0.0,>=3.9.0 (from Levenshtein==0.26.1->python-Levenshtein)
  Downloading rapidfuzz-3.10.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl (18 kB)
Downloading python_Levenshtein-0.26.1-py3-none-any.whl (9.4 kB)
Downloading levenshtein-0.26.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (162 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.6/162.6 kB 7.3 MB/s eta 0:00:00
Downloading rapidfuzz-3.10.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 61.2 MB/s eta 0:00:00
Installing collected packages: fuzzywuzzy, rapidfuzz, Levenshtein, python-Levenshtein
Successfully installed Levenshtein-0.26.1 fuzzywuzzy-0.18.0 python-Levenshtein-0.26.1 rapidfuzz-3.10.1

##Define a function to match the columns, Hubspot and Sage

In [ ]:
from openpyxl import load_workbook
from openpyxl.styles import PatternFill

def check_word_in_column(sheet, source_col, target_col, output_col):
    """
    Checks if a word in the source column exists in the target column and writes 1 for matched,
    0 for not matched, and 0.5 for partial matches.

    Args:
    - sheet: The worksheet object.
    - source_col: The index of the source column (1-based).
    - target_col: The index of the target column (1-based).
    - output_col: The index of the column to store the match results (1-based).
    """

    # Define fill colors for matches, non-matches, and partial matches
    match_fill = PatternFill(start_color="C6EFCE", end_color="C6EFCE", fill_type="solid")  # Green for matched
    partial_fill = PatternFill(start_color="FFA500", end_color="FFA500", fill_type="solid")  # Orange for partial match
    no_match_fill = PatternFill(start_color="FFFF00", end_color="FFFF00", fill_type="solid")  # Yellow for unmatched

    # Get all values from the target column
    target_values = {str(sheet.cell(row=row, column=target_col).value) for row in range(2, sheet.max_row + 1)}

    for row in range(2, sheet.max_row + 1):  # Assuming row 1 contains headers
        source_value = sheet.cell(row=row, column=source_col).value  # Value from the source column
        source_value_str = str(source_value) if source_value is not None else ""

        # Check if the source value is in the target values
        if source_value_str in target_values:
            match_result = 1  # Matched
            sheet.cell(row=row, column=output_col).fill = match_fill  # Apply green fill for matched
        elif any(source_value_str in str(target_value) for target_value in target_values):
            match_result = 0.5  # Partial match
            sheet.cell(row=row, column=output_col).fill = partial_fill  # Apply orange fill for partial matches
        else:
            match_result = 0  # Not matched
            sheet.cell(row=row, column=output_col).fill = no_match_fill  # Apply yellow fill for unmatched

        # Write the result to the output column
        sheet.cell(row=row, column=output_col).value = match_result

##Load the workbook and select the worksheet

In [ ]:
wb = load_workbook('/content/hubspot&sagedata.xlsx')
ws = wb["Sheet1"]

# Define column indices (1-based)
source_col = 1   # words in Column A (hubspot)
target_col = 2   # target column to search in Column B(sage)
output_col = 3   # Column C(match results)

# Check if words from source column are in target column
check_word_in_column(ws, source_col, target_col, output_col)

# Save the file
wb.save("word_match_hubspot_sage.xlsx")

##Display matched column

In [ ]:
df2 = pd.read_excel('/content/word_match_hubspot_sage.xlsx')
df2

      Company Name(hubspot) Company Name(sage)  Unnamed: 2
0                Clayworks               Novex         1.0
1          Franco Finishes             Infinex         1.0
2              Berry Global   mermaid leisure          1.0
3     Dewi Lewis Publishing        Oddcolours          1.0
4           Bricky's Buddy               WSCCL         1.0
...                     ...                ...         ...
3035                    NaN                NaN         0.5
3036   SPECIALIST LOGISTICS                NaN         0.0
3037             Texla DMCC                NaN         0.0
3038   SPECIALIST LOGISTICS                NaN         0.0
3039   SPECIALIST LOGISTICS                NaN         0.0

[3040 rows x 3 columns]

In [ ]:
sheet1 = pd.read_excel('/content/hubspot_data.xlsx')
sheet2 = pd.read_excel('/content/Colab AJ_cleaned_pq.xlsx')

In [ ]:
import pandas as pd

def match_sheets_with_condition(sheet1_path, sheet2_path, key_column, condition_column, condition_value):
    # Load both sheets into DataFrames
    sheet1_df = pd.read_excel(sheet1_path)
    sheet2_df = pd.read_excel(sheet2_path)

    # Merge on the key column to find matches
    matched_df = pd.merge(sheet1_df, sheet2_df, on='Record ID', how='left')

    # Apply the condition and create a new column with the result
    matched_df['Match_Result'] = matched_df[condition_column].apply(
        lambda x: "1" if x == condition_value else "0"
    )

    return matched_df

In [ ]:
matched = match_sheets_with_condition(
    '/content/hubspot_data.xlsx',
    '/content/Colab AJ_cleaned_pq.xlsx',
    'Company Name',
    'Comment',
    'Converted'
)
print(matched)

        Record ID       Tudor Contact         Company Name_x  \
0     57466897290        Adam Johnson          Clayworks Ltd
1     57419121966        Adam Johnson    Franco Finishes Ltd
2     56611537189        Adam Johnson           Berry Global
3     56325263724        Adam Johnson  Dewi Lewis Publishing
4     55413343848        Adam Johnson     Bricky's Buddy Ltd
...           ...                 ...                    ...
3035  23695096734        Adam Johnson                    NaN
3036  23699011645        Adam Johnson   SPECIALIST LOGISTICS
3037  23712767003        Adam Johnson             Texla DMCC
3038  23712771897  Stephen Sunderland   SPECIALIST LOGISTICS
3039  23712773782        Adam Johnson   SPECIALIST LOGISTICS

              Export From                 Import To   Phone Number  \
0                       UK              Saudi Arabia  4.413263e+11
1     United Arab Emirates                     Qatar  4.477112e+11
2                       UK              South Africa  4.477716e+11
3                       UK  United States of America  4.478907e+11
4                       UK                 Australia  4.475405e+11
...                    ...                       ...           ...
3035                    UK                     GHANA           NaN
3036           NETHERLANDS                     SUDAN  9.715852e+11
3037                    UK                     DUBAi  9.715267e+11
3038           NETHERLANDS                     SUDAN  9.714586e+10
3039              PORTUGAL                     SUDAN  9.714586e+10

     Transport Mode Prospect Postcode  COST IN  QUOTE OUT  ...  \
0               Air          TR12 7AZ   1250.0     1395.0  ...
1               Air          GARSTANG   2067.0     2310.0  ...
2               Air          NN10 8RP    427.0      666.0  ...
3           Courier          SG13 7DT    940.0     1135.0  ...
4               Air           DL8 1XF   1116.0     1340.0  ...
...             ...               ...      ...        ...  ...
3035      Sea - LCL             Tudor      NaN        NaN  ...
3036      Sea - LCL         Rotterdam      NaN        NaN  ...
3037            Air           HU3 2DU      NaN        NaN  ...
3038            Air         Rotterdam      NaN        NaN  ...
3039            Air          Portugal      NaN        NaN  ...

             Create Date  Last Modified Date        Job Title  \
0    2024-09-12 15:40:00 2024-09-27 15:57:00              NaN
1    2024-09-12 12:15:00 2024-09-27 15:55:00              NaN
2    2024-09-10 12:31:00 2024-09-27 15:53:00              NaN
3    2024-09-09 14:16:00 2024-09-27 15:52:00              NaN
4    2024-09-06 10:14:00 2024-09-27 15:50:00              NaN
...                  ...                 ...              ...
3035 2024-05-23 12:44:00 2024-05-30 10:20:00              NaN
3036 2024-05-23 12:55:00 2024-05-30 10:19:00              NaN
3037 2024-05-23 13:57:00 2024-05-30 10:18:00  General manager
3038 2024-05-23 14:13:00 2024-05-30 10:17:00              NaN
3039 2024-05-23 14:19:00 2024-05-30 10:17:00              NaN

                 utm_source                   utm_campaign  \
0     DD_google_ads_Q3_2024  international_pallet_shipping
1     DD_google_ads_Q3_2024  international_pallet_shipping
2     DD_google_ads_Q3_2024  international_pallet_shipping
3     DD_google_ads_Q3_2024  international_pallet_shipping
4     DD_google_ads_Q3_2024  international_pallet_shipping
...                     ...                            ...
3035                    NaN                            NaN
3036                    NaN                            NaN
3037                    NaN                            NaN
3038                    NaN                            NaN
3039                    NaN                            NaN

            Company Name_y  Company Name Sage Similarity        Comment  \
0                      NaN                NaN        NaN            NaN
1                      NaN                NaN        NaN            NaN
2                      NaN                NaN        NaN            NaN
3                      NaN                NaN        NaN            NaN
4                      NaN                NaN        NaN            NaN
...                    ...                ...        ...            ...
3035                   NaN                NaN        NaN            NaN
3036  SPECIALIST LOGISTICS  premier logistics       70.0  Not Converted
3037                   NaN                NaN        NaN            NaN
3038  SPECIALIST LOGISTICS  premier logistics       70.0  Not Converted
3039  SPECIALIST LOGISTICS  premier logistics       70.0  Not Converted

     Match_Result
0               0
1               0
2               0
3               0
4               0
...           ...
3035            0
3036            0
3037            0
3038            0
3039            0

[3040 rows x 27 columns]

In [ ]:
matched.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3040 entries, 0 to 3039
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Record ID                3040 non-null   int64
 1   Tudor Contact            3030 non-null   object
 2   Company Name_x           2802 non-null   object
 3   Export From              3009 non-null   object
 4   Import To                3036 non-null   object
 5   Phone Number             2556 non-null   float64
 6   Transport Mode           3032 non-null   object
 7   Prospect Postcode        2980 non-null   object
 8   COST IN                  281 non-null    float64
 9   QUOTE OUT                303 non-null    float64
 10  Last Communication Date  3012 non-null   datetime64[ns]
 11  Given us a job?          305 non-null    object
 12  Source                   384 non-null    object
 13  Regular Customer?        302 non-null    object
 14  Quote Details            3040 non-null   object
 15  Lead Status              0 non-null      float64
 16  Last Activity Date       14 non-null     datetime64[ns]
 17  Create Date              3040 non-null   datetime64[ns]
 18  Last Modified Date       3040 non-null   datetime64[ns]
 19  Job Title                94 non-null     object
 20  utm_source               93 non-null     object
 21  utm_campaign             93 non-null     object
 22  Company Name_y           864 non-null    object
 23  Company Name Sage        864 non-null    object
 24  Similarity               864 non-null    float64
 25  Comment                  864 non-null    object
 26  Match_Result             3040 non-null   object
dtypes: datetime64[ns](4), float64(5), int64(1), object(17)
memory usage: 641.4+ KB

In [ ]:
matched2 = pd.read_excel('/content/Tudor_finalmerge_AB 050125.xlsx')

In [ ]:
matched2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2372 entries, 0 to 2371
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Record ID                2372 non-null   int64
 1   Tudor Contact            2366 non-null   object
 2   Company Name_x           2372 non-null   object
 3   Export From              2346 non-null   object
 4   Import To                2369 non-null   object
 5   Transport Mode           2366 non-null   object
 6   Prospect Postcode        2332 non-null   object
 7   COST IN                  226 non-null    float64
 8   QUOTE OUT                2367 non-null   float64
 9   Last Communication Date  2352 non-null   object
 10  Given us a job?          195 non-null    object
 11  Source                   311 non-null    object
 12  Regular Customer?        195 non-null    object
 13  Quote Details            2372 non-null   object
 14  Lead Status              0 non-null      float64
 15  Last Activity Date       9 non-null      float64
 16  Create Date              2372 non-null   datetime64[ns]
 17  Last Modified Date       2372 non-null   datetime64[ns]
 18  Job Title                83 non-null     object
 19  utm_source               80 non-null     object
 20  utm_campaign             80 non-null     object
 21  Company Name_y           771 non-null    object
 22  Company Name Sage        771 non-null    object
 23  Similarity               771 non-null    float64
 24  Comment                  771 non-null    object
 25  Match_Result             2372 non-null   int64
 26  Quote Details.1          1324 non-null   float64
dtypes: datetime64[ns](2), float64(6), int64(2), object(17)
memory usage: 500.5+ KB

In [ ]:
matched3 = pd.read_excel('/content/Tudordata3_analysis1.xlsx')

In [ ]:
matched3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2371 entries, 0 to 2370
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Record ID                2371 non-null   int64
 1   Tudor Contact            2371 non-null   object
 2   Company Name             2371 non-null   object
 3   Export From              2371 non-null   object
 4   Import To                2371 non-null   object
 5   Transport Mode           2371 non-null   object
 6   Prospect Postcode        2371 non-null   object
 7   COST IN                  2371 non-null   float64
 8   QUOTE OUT                2371 non-null   float64
 9   Last Communication Date  2371 non-null   object
 10  Create Date              2371 non-null   datetime64[ns]
 11  Last Modified Date       2371 non-null   datetime64[ns]
 12  Match_Result             2371 non-null   object
 13  Year                     2371 non-null   int64
 14  Month                    2371 non-null   int64
 15  Day                      2371 non-null   int64
 16  Month Name               2371 non-null   object
dtypes: datetime64[ns](2), float64(2), int64(4), object(9)
memory usage: 315.0+ KB

In [ ]:
matched.to_excel("new_matched_results.xlsx", index=False)

In [ ]:
import pandas as pd
import re

# Load the Excel file
file_path = "data.xlsx"  # Replace with your file path
df = pd.read_excel(new_matched_results.xlsx)

# Define the function to extract numbers with the pound sign
def extract_pound_numbers(text):
    if pd.notna(text):  # Ensure the text is not NaN
        # Extract numbers with a pound sign using regex
        matches = re.findall(r'£\d+', str(text))  # Matches '£' followed by digits
        return ', '.join(matches)  # Join results as a comma-separated string
    return ''

# Apply the function to the desired column
df['Pound Numbers'] = df['TextColumn'].apply(extract_pound_numbers)

# Save the updated data back to the Excel file
output_path = "output.xlsx"
df.to_excel(output_path, index=False)

print(f"Pound-signed numbers extracted and saved to '{output_path}'.")

NameError: name 'new_matched_results' is not defined